[package]
name = "advent_of_code_2020_day_1"
version = "0.1.0"
authors = ["valrus <imccowan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
